export const possibleVoices = [
    "21m00Tcm4TlvDq8ikWAM",
    "29vD33N1CtxCmqQRPOHJ",
    "2EiwWnXFnvU5JabPnv8n",
    "5Q0t7uMcjvnagumLfvZi",
    "AZnzlk1XvdvUeBnXmlld",
    "CYw3kZ02Hs0563khs1Fj",
    "D38z5RcWu1voky8WS1ja",
    "EXAVITQu4vr4xnSDxMaL",
    "ErXwobaYiN019PkySvjV",
    "GBv7mTt0atIp3Br8iCZE",
    "IKne3meq5aSn9XLyUdCD",
    "JBFqnCBsd6RMkjVDRZzb",
    "LcfcDJNUP1GQjkzn1xUU",
    "MF3mGyEYCl7XYWbV9V6O",
    "N2lVS1w4EtoT3dr4eOWO",
    "ODq5zmih8GrVes37Dizd",
    "SOYHLrjzK2X1ezoPC6cr",
    "TX3LPaxmHKxFdv7VOQHJ",
    "ThT5KcBeYPX3keUQqHPh",
    "TxGEqnHWrfWFTfGW9XjX",
    "VR6AewLTigWG4xSOukaG",
    "XB0fDUnXU5powFXDhCwa",
    "XrExE9yKIg1WjnnlVkGX",
    "Yko7PKHZNXotIFUBG7I9",
    "ZQe5CZNOzWyzPSCn5a3c",
    "Zlb1dXrM653N07WRdFW3",
    "bVMeCyTHy58xNoL34h3p",
    "flq6f7yk4E4fJM5XTYuZ",
    "g5CIjZEefAph4nQFvHAz",
    "jBpfuIE2acCO8z3wKNLl",
    "jsCqWAovK2LkecY7zXl4",
    "knrPHWnBmmDHMoiMeP3l",
    "oWAxZDx7w5VEj9dCyTzz",
    "onwK4e9ZLuTAKqWW03F9",
    "pFZP5JQG7iQjIQuC4Bku",
    "pMsXgVXv3BLzUgSXRplE",
    "pNInz6obpgDQGcFmaJgB",
    "piTKgcLEGmPE4e6mEKli",
    "pqHfZKP75CvOlQylNhV4",
    "t0jbNlBVZ17f02VDIeMI",
    "yoZ06aMxZJJ28mfd3POQ",
    "z9fAnlkpzviPz146aGWa",
    "zcAOhNBS3c14rBihAFp1",
  ];
  
  export const prefixes = [
    "pesquisar sobre",
    "entender melhor",
    "estudar",
    "acreditar em",
    "saber mais de",
    "chegar a",
    "saber tudo de",
    "contar com",
    "ler a respeito de",
    "investigar",
    "descobrir sobre",
    "se atualizar sobre",
    "tuitar sobre",
    "ter uma opinião sobre",
  ];
  
  export const poemArray = [
    "É preciso casar João,",
    "é preciso suportar Antônio,",
    "é preciso odiar Melquíades",
    "é preciso substituir nós todos.",
    "É preciso salvar o país,",
    "é preciso crer em Deus,",
    "é preciso pagar as dívidas,",
    "é preciso comprar um rádio,",
    "é preciso esquecer fulana.",
    "É preciso estudar volapuque,",
    "é preciso estar sempre bêbado,",
    "é preciso ler Baudelaire,",
    "é preciso colher as flores de que rezam velhos autores.",
  ];

  export const lastStanza = `É preciso viver com os homens\né preciso não assassiná-los,\né preciso ter mãos pálidas\ne anunciar O FIM DO MUNDO.`;
